// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://czjgbvupjrkihilofdre.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImN6amdidnVwanJraWhpbG9mZHJlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM0OTQ0NTYsImV4cCI6MjA2OTA3MDQ1Nn0.gK-2xitMo4mVMm99tV2QYJW5RjERRY1W0ydkgc2Ghp8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});